version: "3"
services:
  web:
    build:
      context: .
      target: api
    restart: always
    expose:
     - 5001
    depends_on:
      - redis
      - neo4j
    volumes:
      - static_volume:/app/static
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - 'db:/data'
  worker:
    build:
      context: .
      target: worker
    depends_on:
      - redis
      - neo4j
  redis:
    image: redis:latest
  nginx:
    build:
      context: .
      target: nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
volumes:
  db:
  static_volume:
